#!/usr/bin/env bash

if [[ $1 == "env" ]] ; then
    echo "Setting up virtual environment..."
    pip3 install virtualenv
    virtualenv --python=python$3 $2
    source $2/bin/activate
    #pip3 install -r requirements.txt
    pip3 install opencv-python
    source deactivate

    echo "Virtual environment setup complete."
    echo "To activate the virtual environment, run:"
    echo "source $2/bin/activate"
    echo "To deactivate the virtual environment, run:"
    echo "deactivate"
    exit 0
else 
    pip3 install -r requirements.txt
    exit 0
fi
